#!/bin/bash
set -euo pipefail

# Generate js/supabase-config.js from environment variables (Vercel build step).
# If env vars are missing the app falls back to offline/localStorage mode.

CONFIG_FILE="js/supabase-config.js"

if [ -z "${SUPABASE_URL:-}" ] || [ -z "${SUPABASE_ANON_KEY:-}" ]; then
    echo "INFO: SUPABASE_URL or SUPABASE_ANON_KEY not set. Skipping config generation (offline mode)."
    exit 0
fi

# Write config file
cat > "$CONFIG_FILE" <<'HEREDOC_END'
// Auto-generated by build.sh — do not edit
HEREDOC_END

# Append the actual values (variable substitution happens here, not inside heredoc)
printf "const SUPABASE_URL = '%s';\n" "$SUPABASE_URL" >> "$CONFIG_FILE"
printf "const SUPABASE_ANON_KEY = '%s';\n" "$SUPABASE_ANON_KEY" >> "$CONFIG_FILE"

# Validate the generated file
if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: $CONFIG_FILE was not created." >&2
    exit 1
fi

if ! grep -q 'SUPABASE_URL' "$CONFIG_FILE" || ! grep -q 'SUPABASE_ANON_KEY' "$CONFIG_FILE"; then
    echo "ERROR: $CONFIG_FILE is missing expected declarations." >&2
    exit 1
fi

echo "OK: $CONFIG_FILE generated successfully."
